variables:
  APP_NAME: "Medi_App"

image: maven:latest

stages:
  - build
  - test
  - deploy

buildStep:
  image: maven:3-jdk-8
  stage: build
  tags:
    - dalfcs_docker_kvm
  before_script:
    - docker login -u antor007 -p pM;P&tcC~*y6G9= localhost:8080
  script:
    - mvn clean compile
  only:
    - develop

testStep:
  image: maven:3-jdk-8
  stage: test
  tags:
    - dalfcs_docker_kvm
  before_script:
    - docker login -u antor007 -p pM;P&tcC~*y6G9= localhost:8080
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
  script:
    mvn verify
  only:
    - develop

deployStep:
  stage: deploy
  tags:
    - dalfcs_docker_kvm
  before_script:
    - 'command -v ssh-agent >/dev/null || ( yum update -y && yum install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - mvn package
  artifacts:
    paths:
      - target/centrailized_medi_application-1.0-SNAPSHOT.jar
  script:
    - ssh -o StrictHostKeyChecking=no ${PROD_DEPLOY_USER}@${DEPLOY_HOST} "mkdir ${DEPLOY_DIR}/${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}"
    - scp -r -o StrictHostKeyChecking=no target/centrailized_medi_application-1.0-SNAPSHOT.jar "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}_${APP_NAME}.jar"
  only:
    - release